language: node
addons:
  ssh_known_hosts: frostming.com
cache:
  yarn: true
  directories:
    - static/node_modules
services:
  - docker
before_install: npm i -g yarn && yarn
install: cd static && yarn install && yarn run build:prod
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t flog .
  - docker run -d --name app flog
script:
  - docker exec app python -m unittest
after_script:
  - docker rm -f app

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c7c8aa0cde62_key -iv $encrypted_c7c8aa0cde62_iv
    -in mysecret.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: master
notifications:
  email: false
env:
  global:
    secure: K+WDXek/x0v2q8A67KEBNtTT5FHwo7OGZ2oD1pn4gJ9zHCUiPUE1Dv8RCm/TktNbDIpU3BckP9sOHu7Mq1RKjooEJVdwnS54+HuJNfFS9ii3Spude4hvuSzAM12o/gRQqVOldrqVvtW8Evx/BPGQBiGXqKpAdyhsQgNuTozRuBxyBfxrmrprFIcvGBk6v2b406wSSHC8W6hc6WomF/5Mba81JcPh25QfR8cglso8IW6Xaz+jNQxk88sr+M/sZWpeaHnen1kjEn+h8MN+gzHNs3wGh3ao2hbkp+XT3G3eh19KWv6YUa5JJXn4NyMrRbulhPcNv0/ZEdwsDXAQ7C7LDXbEPFqja+27SUq+CeXKVipVKyNFhgi8bBDlhMR1t4dwW28Uls2DRugfw8XG/uLQoxNC5YEHNtZYK7gSld1lofTK/tQmshFNfQ84ol328P9gx6Rgm3v0A+yt9adAX2Nh08YLptq4Ib21lcD3CIklG7pBCRdkXI6dAUZueAoZPxn2IqSj6P1wbcrYCu5ZMjlGFlorAJ1gaZof9HyqZSWSpOvUFA3TVBVM146C4gLdtd8WiA5LwWFlL2t4ESDlD1froPkBb8lQiXjUXT/ic4CXRKAobR6lEvD16KcnauhYy1NgtkcFgRRM5XFdhEcWIN0S5rKVGbmoq2Llct4NgCLY+GY=
